export const links = {
    sourceCode: 'https://github.com/ikaushiksharma/costkeeper',
} as const

import type { Metadata } from 'next'

export const siteConfig: Metadata = {
    title: 'CostKeeper',
    description: 'Track your income and expenses with CostKeeper.',
    keywords: [
        'reactjs',
        'nextjs',
        'vercel',
        'react',
        'drizzle-orm',
        'drizzle',
        'shadcn',
        'shadcn-ui',
        'radix-ui',
        'cn',
        'clsx',
        'finance-app',
        'transactions',
        'dashboard',
        'accounts',
        'clerk',
        'neon-db',
        'sonner',
        'zustand',
        'zod',
        'sql',
        'postgresql',
        'honojs',
        'honojs-api',
        'hono-api',
        'lucide-react',
        'recharts',
        'postcss',
        'prettier',
        'react-dom',
        'tailwindcss',
        'tailwindcss-animate',
        'ui/ux',
        'js',
        'javascript',
        'typescript',
        'eslint',
        'html',
        'css',
    ] as Array<string>,
    authors: {
        name: 'Kaushik Sharma',
        url: 'https://github.com/ikaushiksharma',
    },
} as const
